service:
  name: image-processor
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

custom:
  bucket_name: image-processor-photos
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
  s3:
    photosBucket:
      name: ${self:custom.bucket_name}
      accessControl: PublicReadWrite
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
        - "s3:GetObject"
        - "s3:PutObject"
      Resource: "arn:aws:s3:::${self:custom.bucket_name}/*"

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello

  createThumbnails:
    handler: handler.createThumbnails
    events:
      - s3:
          bucket: ${self:custom.bucket_name}
          event: s3:ObjectCreated:*
